# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token ab0bc5cdbe471f6221f6c6c1381ef6a1fca099a1

{
  "title": "Шкаф IKEA",
  "description": "Срочно",
  "status": "CLOSED"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token d20cb8b8f66c6ba193337761cebaa8029f59c0f7

{
  "status": "CLOSED"
}

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2023-07-12
Content-Type: application/json

###

# удаление
DELETE  {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token d20cb8b8f66c6ba193337761cebaa8029f59c0f7