# Generated by Django 4.2.1 on 2023-05-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_tag_options_tag_articles_alter_scope_is_mane_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='is_mane',
            new_name='is_main',
        ),
    ]
